# Generated by Django 3.1 on 2020-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cont',
            field=models.TextField(default='yes'),
        ),
    ]
