# Generated by Django 3.1 on 2020-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cont',
        ),
    ]
