# Generated by Django 3.1 on 2020-09-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
